apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: {{ include "ct.name" . }}
spec:
  workspaces:
    - name: source
  params:
    - name: IMAGE
      description: image
      type: string
    - name: NAMESPACE
      type: string
    - name: COSIGN_VERSION
      type: string
      description: Version of cosign CLI
      default: 1.6.0
  steps:
    - name: image-signing
      image: quay.io/openshift/origin-cli:4.16
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash

        curl -skL -o /tmp/cosign https://github.com/sigstore/cosign/releases/download/v$(params.COSIGN_VERSION)/cosign-linux-amd64

        chmod -R 775 /tmp/cosign

        TENANT_NAME=$(echo $(params.NAMESPACE) | rev | cut -d '-' -f2- | rev)

        echo "Tenant name is " $TENANT_NAME

        echo "Image name is " $(params.IMAGE)

        /tmp/cosign sign -key k8s://$TENANT_NAME-build/cosign-key-password $(params.IMAGE)
        
