apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
    name: {{ include "stakater-helm-push.name" . }}
spec:
  description: >-
    helm-push installs helm push, increase version based on tag (if main)
    or from Char.yaml (if PR or branch). Finally it saves the tag to GIT_TAG
    file in a pre checked out helm repository in the *source* workspace and push
    the packed chart to the chartmuseum defined in *registry*
  params:
    - name: REPO_PATH
      type: string
    - name: REGISTRY
      type: string
    - default: NA
      name: PR_NUMBER
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - name: SEM_VER
      default: "1.0.0"
  workspaces:
  - name: source
  steps:
  - env:
    - name: REG_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: nexus-helm-auth-forked
          optional: true
    - name: REG_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: nexus-helm-auth-forked
          optional: true
    image: stakater/pipeline-toolbox:v0.0.20
    name: helm-package
    command: ["/bin/bash"]
    workingDir: $(workspaces.source.path)
    args:
      - -c
      - |
          set -e
          if [ $(params.prnumber) == "NA" ] && ( [ $(params.gitrevision) == "main" ] || [ $(params.gitrevision) == "master" ] ); then
             REPO=$(echo $(inputs.params.repoPath) | rev | cut -d'/' -f 1 | rev )
             VERSION=$(inputs.params.semVer)
             CHART_PACKAGE="$(helm package --version $VERSION -u deploy | cut -d":" -f2 | tr -d '[:space:]')"
             echo Uploading $CHART_PACKAGE to $(params.registry)
             curl -u "${REG_USER}":"${REG_PASSWORD}" $(params.registry) --upload-file "$CHART_PACKAGE"
           echo "Helm chart successfully pushed"
          else
              echo "Its a PR"
          fi
