name: Stakater github update cd repo cluster task Helm Chart
on:
  pull_request:
    branches:
    - main
    paths:
    - 'stakater-github-update-cd-repo/**'

  push:
    branches:
    - main
    paths:
    - 'stakater-github-update-cd-repo/**'
    - '.github/workflows/stakater_github_update_cd_repo.yaml'

jobs:
  next-version:
    uses: stakater/tekton-catalog/.github/workflows/next_version.yaml@main
    with:
      component: stakater-github-update-cd-repo

  pull-request:
    uses: stakater/tekton-catalog/.github/workflows/pull_request.yaml@main
    name: Pull Request
    if: ${{ github.ref != 'refs/heads/main' }}
    needs:
    - next-version
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    with:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      HELM_REGISTRY_URL: oci://ghcr.io/stakater/charts
      SUBPATH: stakater-github-update-cd-repo
      PUSH_CONTAINER_IMAGE: ${{ needs.next-version.outputs.dockerfile_exists }}
      PUBLISH_HEM_CHART: ${{ needs.next-version.outputs.helm_chart_exists }}
      NEXT_VERSION: ${{ needs.next-version.outputs.version }}

  push-and-release:
    uses: stakater/tekton-catalog/.github/workflows/push.yaml@main
    name: Push and Release
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
    - next-version
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    with:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      HELM_REGISTRY_URL: oci://ghcr.io/stakater/charts
      SUBPATH: stakater-github-update-cd-repo
      PUSH_CONTAINER_IMAGE: ${{ needs.next-version.outputs.dockerfile_exists }}
      PUBLISH_HEM_CHART: ${{ needs.next-version.outputs.helm_chart_exists }}
      NEXT_VERSION: ${{ needs.next-version.outputs.version }}

  render-and-replace:
    uses: stakater/tekton-catalog/.github/workflows/render_task.yaml@main
    name: Render and Replace
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
      - next-version
    secrets:
      STAKATER_GITHUB_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
    with:
      SUBPATH: stakater-github-update-cd-repo
      NEXT_VERSION: ${{ needs.next-version.outputs.version }}